import { Layout } from 'antd'
import Head from 'next/head'
import HeaderTemplate from './header'
import styles from '../styles/Online.module.css'

const { Footer, Content } = Layout

type Props = {
  children: JSX.Element | JSX.Element[] | string
}

const TemplateOnline = ({ children }: Props) => {
  return (
    <Layout className={styles.template}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderTemplate />
      <Content className={styles.content}>
        <Layout className={styles.pageContainer}>{children}</Layout>
      </Content>
      <Footer className={styles.footer}>Teste</Footer>
    </Layout>
  )
}

export default TemplateOnline
