import { Layout, Spin } from 'antd'
import Head from 'next/head'
import HeaderTemplate from './header'
import styles from '../styles/Online.module.css'
import { RootState, useAppDispatch, useAppSelector } from '~/store/store-config'
import { useEffect } from 'react'
import { getAuthUserOnReload } from '~/store/user/get-auth-user-reload'
import { useRouter } from 'next/router'
import { UserActions } from '~/store/user/user-reducer'

const { Footer, Content } = Layout

type Props = {
  children: JSX.Element | JSX.Element[] | string
}

const TemplateOnline = ({ children }: Props) => {
  const dispatch = useAppDispatch()
  const router = useRouter()
  const isPending = useAppSelector((state: RootState) => state.user.isPending)

  useEffect(() => {
    dispatch(UserActions.setIsPending(true))
    getAuthUserOnReload(dispatch, router)
  }, [])

  return (
    <Layout className={styles.template}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spin spinning={isPending}>
        <HeaderTemplate />
        <Content className={styles.content}>
          <Layout className={styles.pageContainer}>{children}</Layout>
        </Content>
        <Footer className={styles.footer}>Teste</Footer>
      </Spin>
    </Layout>
  )
}

export default TemplateOnline
